name = "passing test"
submission_number = 371
url = "https://passing test"
description = "passing test"
contact_info = "passing test"
labels = []
group = "Transpiler plugin"
packages = []
uuid = "6c037525-3b57-4071-9654-cd3291f435b8"
