name = "project 1"
submission_number = 435
url = "https://project 1"
description = "project 1"
labels = []
website = "project 1"
group = "Unitary synthesis plugin"
documentation = "project 1"
packages = [ "project 1",]
uuid = "4d6f21d3-af14-499b-96a7-d51e59dde47c"
