name = "project 20"
submission_number = 419
url = "https://project 20"
description = "project 20"
labels = [ "Rust",]
group = "Unitary synthesis plugin"
packages = []
uuid = "12f7d478-c634-4318-a268-99ba0840ac7b"
