name = "project 40"
submission_number = 433
url = "https://github.com/Qiskit/ecosystem"
description = "project 40"
labels = []
group = "Unitary synthesis plugin"
packages = []
uuid = "b4070cdc-68d4-47c3-933a-e7f3d8bf3b28"
