name = "project 30"
submission_number = 423
url = "https://project 30"
description = "project 30"
labels = [ "Java",]
group = "Transpiler plugin"
packages = []
uuid = "0d4b182f-4d6c-4d81-b442-3f4eb9fc6764"
