name = "project 10"
submission_number = 413
url = "https://project 10"
description = "project 10"
labels = [ "error correction",]
group = "Unitary synthesis plugin"
packages = []
uuid = "ef8821f7-7f6d-4552-be6a-ec67fe8e690f"
