name = "project 34"
submission_number = 431
url = "https://project 34"
description = "project 34"
labels = []
group = "Unitary synthesis plugin"
packages = []
uuid = "b6013a90-65c3-4d40-bead-df29ba0bfcfd"
