name = "project 8"
submission_number = 409
url = "https://project 8"
description = "project 8"
labels = [ "error correction",]
group = "Transpiler plugin"
packages = []
uuid = "f243b213-f013-42d0-a690-e34194a045ee"
