name = "project 9"
submission_number = 411
url = "https://project 9"
description = "project 9"
labels = [ "error correction",]
group = "Unitary synthesis plugin"
packages = []
uuid = "a4295f45-fb69-4526-ab4e-4a69a07c5bf7"
