name = "project 21"
submission_number = 421
url = "https://github.com/1ucian0/ecosystem"
description = "project 21"
contact_info = "project 21"
labels = [ "Java",]
group = "Transpiler plugin"
packages = []
uuid = "96b40182-d399-4ec1-b1e0-82fc54d7712e"
