name = "project 14"
submission_number = 417
url = "https://project 14"
description = "project 14"
labels = [ "error correction",]
group = "Transpiler plugin"
packages = []
uuid = "6cba1363-d8ae-48a7-a9f6-82838567f081"
