name = "project 11"
submission_number = 415
url = "https://project 11"
description = "project 11"
labels = [ "error correction",]
group = "Unitary synthesis plugin"
packages = []
uuid = "327f77c4-3738-4950-996c-65eca8dcc2d8"
